version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: bank
    volumes:
      - postgres_data:/var/lib/postgresql@16/data
    ports:
      - "0.0.0.0:5432:5432"

volumes:
  postgres_data: