server:
  port: 9090

spring:
  application:
    name: ThorstenHagaInterview
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:interview;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    out-of-order: true

